import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import esbuildSvelte from "esbuild-svelte";
import { sveltePreprocess } from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

// Debug flags - set to true for development debugging
// These are replaced at build time and dead-code-eliminated in production
const DEBUG_ENABLED = false;
const DEBUG_RENDERS = false; // Set to false to disable render logging in dev
const DEBUG_DRAG = false; // Set to false to disable drag logging in dev
const DEBUG_SCROLL = false; // Set to true to enable scroll logging in dev
const DEBUG_CACHE = false; // Set to false to disable cache logging in dev

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		DEBUG_ENABLED: String(DEBUG_ENABLED),
		DEBUG_RENDERS: String(DEBUG_RENDERS),
		DEBUG_DRAG: String(DEBUG_DRAG),
		DEBUG_SCROLL: String(DEBUG_SCROLL),
		DEBUG_CACHE: String(DEBUG_CACHE),
	},
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
		}),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
}

await context.watch();
