import {
  BACKGROUND_BLUR_OPTION_KEY,
  BACKGROUND_BRIGHTNESS_OPTION_KEY,
  BACKGROUND_IMAGE_OPTION_KEY,
  CARD_COVER_ENABLED_OPTION_KEY,
  CARD_COVER_CONTAIN_OPTION_KEY,
  CARD_COVER_HEIGHT_OPTION_KEY,
  CARD_COVER_SOURCE_OPTION_KEY,
  COLUMN_BLUR_OPTION_KEY,
  COLUMN_ORDER_OPTION_KEY,
  COLUMNS_RIGHT_TO_LEFT_OPTION_KEY,
  COLUMN_TRANSPARENCY_OPTION_KEY,
  KANBAN_VIEW_ID_OPTION_KEY,
  LOCAL_CARD_ORDER_OPTION_KEY,
  PINNED_COLUMNS_OPTION_KEY,
} from "./constants";

export function getKanbanViewOptions() {
  return [
    {
      key: COLUMN_ORDER_OPTION_KEY,
      displayName: "Column order",
      type: "text" as const,
      default: "",
      placeholder: "Managed by drag and drop",
      shouldHide: () => true,
    },
    {
      key: LOCAL_CARD_ORDER_OPTION_KEY,
      displayName: "Card order",
      type: "text" as const,
      default: "",
      placeholder: "Managed by drag and drop",
      shouldHide: () => true,
    },
    {
      key: PINNED_COLUMNS_OPTION_KEY,
      displayName: "Pinned columns",
      type: "text" as const,
      default: "",
      placeholder: "Managed by pin button",
      shouldHide: () => true,
    },
    {
      key: KANBAN_VIEW_ID_OPTION_KEY,
      displayName: "Kanban view ID",
      type: "text" as const,
      default: "",
      placeholder: "Managed by Bases Kanban",
      shouldHide: () => true,
    },
    {
      key: BACKGROUND_IMAGE_OPTION_KEY,
      displayName: "Background image",
      type: "text" as const,
      default: "",
      placeholder: "https://... (loads remote URL) or vault/path.png",
    },
    {
      key: BACKGROUND_BRIGHTNESS_OPTION_KEY,
      displayName: "Background brightness",
      type: "slider" as const,
      default: 100,
      min: 0,
      max: 100,
      step: 5,
    },
    {
      key: BACKGROUND_BLUR_OPTION_KEY,
      displayName: "Background blur",
      type: "slider" as const,
      default: 0,
      min: 0,
      max: 20,
      step: 1,
    },
    {
      key: COLUMN_TRANSPARENCY_OPTION_KEY,
      displayName: "Column transparency",
      type: "slider" as const,
      default: 100,
      min: 0,
      max: 100,
      step: 5,
    },
    {
      key: COLUMN_BLUR_OPTION_KEY,
      displayName: "Column blur (macOS translucent window may ghost)",
      type: "slider" as const,
      default: 0,
      min: 0,
      max: 20,
      step: 1,
    },
    {
      key: CARD_COVER_ENABLED_OPTION_KEY,
      displayName: "Show card cover",
      type: "toggle" as const,
      default: true,
    },
    {
      key: CARD_COVER_SOURCE_OPTION_KEY,
      displayName: "Card cover source",
      type: "text" as const,
      default: "cover",
      placeholder: "Frontmatter property name (e.g. cover)",
    },
    {
      key: CARD_COVER_HEIGHT_OPTION_KEY,
      displayName: "Card cover height",
      type: "slider" as const,
      default: 140,
      min: 60,
      max: 200,
      step: 10,
    },
    {
      key: CARD_COVER_CONTAIN_OPTION_KEY,
      displayName: "Image fit: Contain (height ignored)",
      type: "toggle" as const,
      default: false,
    },
    {
      key: COLUMNS_RIGHT_TO_LEFT_OPTION_KEY,
      displayName: "Columns right to left",
      type: "toggle" as const,
      default: false,
    },
  ];
}
